version: "3.3"
services:
  h5ai:
    image: mythevalentinus/h5ai-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: h5ai
    environment:
      USERNAME: user
      PASSWORD: pass
    volumes:
      - h5ai:/h5ai
      - ../repository:/data
      - ./options.json:/h5ai/_h5ai/private/conf/options.json
      - ./types.json:/h5ai/_h5ai/private/conf/types.json
    ports:
      - 80:80/tcp
volumes:
  h5ai:
    driver: local
